### PR TITLE
Fix undefined property

### PR DESCRIPTION
**Pull request by niccifor**
PHP Notice:  Undefined property: ThirtyBees\PostNL\Entity\Shipment::$DeliveryTimestampEnd in /home/betech/Desktop/postnl-api-php-tb/src/Entity/AbstractEntity.php on line 142

- replaced is_null with empty (fixes undefined property)
- updated code example in README to a working one

### CODE REVIEW

**Comment by firstred** [comment]
Thanks a lot for your pull request. Also very nice update for the example.

Just checked the `AbstractEntity.php` changes. Is `empty` the way to go? I believe we should allow values like `0` and `false` as well, just not `null` and undefined values (these should not end up in the call to the PostNL API). Maybe a combination of `isset` and `is_null` would be a better fit?

**Comment by niccifor** [comment]
I’m happy to help.

Agree on that, but if you only want non-null, then ```isset``` should be enough? ([PHP Manual](http://php.net/manual/en/function.isset.php) > Determine if a variable is set and is not NULL.)

**Comment by firstred** [comment]
Ahh yes, it's exactly what we need here :)

Thanks. Will merge it soon!

**Comment by niccifor** [comment]
Great!

p.s. Well written API, I guess only one on github to support new API keys and REST (exactly what we needed). Keep up the good work! I hope that stable release will come soon.

**Comment by firstred** [comment]
Merged. Thank you!

**Pull request merged**
