### PR TITLE
fix: remove types from logger interface due to php compatibility issues

### PR DESCRIPTION
**Pull request by Swahjak**
See #93

### CODE REVIEW

**Comment by Swahjak** [comment]
Another approach would be to set the PHP level in composer.json to ^8.3 (or is it 8.2, not sure)

**Comment by firstred** [comment]
Thanks for the PR. Do you know what the cause is for the incompatibility? Does it only occur on PHP versions below 8.2? Or some incompatibility between the psr/log versions?

I'd rather not remove the types, so if you know a way to keep the types and ensure compatibility then that'd be preferred. By keeping the types, we should be able to avoid a breaking change.

In order to prevent regressions a new test may be needed as well. If you could provide a reproducible case, that'd be appreciated.
 
I'll look into the issue as well, see if I can find more info. I'll share it here.

Thanks again for the PR!

**Comment by firstred** [comment]
I think that the `DummyLogger` can be avoided altogether, since [php-fig/log](https://github.com/php-fig/log/blob) already provides a [`NullLogger`](https://github.com/php-fig/log/blob/3.0.0/src/NullLogger.php) which does exactly the same. Using the built-in dummy logger ensures compatibility between all the different versions of the logger interface.

**Comment by firstred** [comment]
Does https://github.com/firstred/postnl-api-php/pull/96 work for you?

**Comment by Swahjak** [comment]
Sure! Thanks for the quick response

**Comment by firstred** [comment]
A new release has been made with #96: https://github.com/firstred/postnl-api-php/releases/tag/v2.0.9

**Pull request closed without merging**
